import type {
  InvestmentQuoteItem,
  InvestmentQuotesLoadingConfig,
} from "@/types/InvestmentQuotesLoading";

export const INVESTMENT_QUOTES_CONFIG: InvestmentQuotesLoadingConfig = {
  intervalMs: 6000,
  badgeText: "Wealth Wisdom & Strategy",
  tipHeading: "Actionable Investment Tip",
  fetchingNotice: "Syncing real-time market data from SerpApi...",
  quotePrefix: "“",
  quoteSuffix: "”",
  prevButtonAria: "Previous wealth quote",
  nextButtonAria: "Next wealth quote",
  pauseAria: "Pause automatic quote rotation",
  resumeAria: "Resume automatic quote rotation",
};

export const INVESTMENT_QUOTES: InvestmentQuoteItem[] = [
  {
    id: "quote-buffett",
    author: "Warren Buffett",
    title: "Chairman & CEO, Berkshire Hathaway",
    netWorth: "$145 Billion+",
    category: "Patience & Value",
    quote: "The stock market is a device for transferring money from the impatient to the patient.",
    tip: "Invest in businesses with enduring competitive moats, understand their fundamentals, and hold them with a multi-decade mindset rather than trading daily noise.",
  },
  {
    id: "quote-munger",
    author: "Charlie Munger",
    title: "Vice Chairman, Berkshire Hathaway",
    netWorth: "Legendary Value Architect",
    category: "Compounding Mastery",
    quote: "The big money is not in the buying and the selling, but in the waiting.",
    tip: "Resist the urge of hyperactivity. Great compounders reward those who allow time and uninterrupted exponential growth to work their magic.",
  },
  {
    id: "quote-jhunjhunwala",
    author: "Rakesh Jhunjhunwala",
    title: "The Big Bull of Dalal Street",
    netWorth: "Titan of Indian Equities",
    category: "Conviction & Growth",
    quote: "Never invest in a company that you don't understand, and never follow tips blindly. Trends are your friends, but conviction is your anchor.",
    tip: "Focus deeply on long-term structural economic growth. Identify sector leaders before the broad crowd and ride multi-year earnings expansion.",
  },
  {
    id: "quote-lynch",
    author: "Peter Lynch",
    title: "Legendary Manager, Fidelity Magellan Fund",
    netWorth: "Achieved 29.2% Annualized Return",
    category: "Clarity & Simplicity",
    quote: "Know what you own, and know why you own it. If you can't explain it in two minutes to a 10-year-old, you shouldn't own it.",
    tip: "Look for opportunities in everyday consumption. Superior consumer franchises with pricing power often outperform complex, opaque financial instruments.",
  },
  {
    id: "quote-graham",
    author: "Benjamin Graham",
    title: "Father of Value Investing & Buffett's Mentor",
    netWorth: "Dean of Wall Street",
    category: "Margin of Safety",
    quote: "In the short run, the market is a voting machine, but in the long run, it is a weighing machine.",
    tip: "Always demand an adequate margin of safety before allocating capital. Price is what you pay; intrinsic business value is what you receive.",
  },
  {
    id: "quote-dalio",
    author: "Ray Dalio",
    title: "Founder, Bridgewater Associates",
    netWorth: "$15 Billion+",
    category: "Risk Architecture",
    quote: "Diversification is the holy grail of investing. Finding 15 or more uncorrelated return streams reduces risk without sacrificing return.",
    tip: "Manage downside risk aggressively before chasing upside. Understand macroeconomic debt cycles and balance exposure across uncorrelated assets.",
  },
  {
    id: "quote-bogle",
    author: "John C. Bogle",
    title: "Founder, The Vanguard Group",
    netWorth: "Father of Low-Cost Indexing",
    category: "Fee Efficiency",
    quote: "Don't look for the needle in the haystack. Just buy the haystack.",
    tip: "Keep investment costs, taxes, and turnover friction near zero. Over decades, compounding fee drag destroys wealth faster than standard market corrections.",
  },
  {
    id: "quote-naval",
    author: "Naval Ravikant",
    title: "Co-Founder, AngelList & Modern Philosopher",
    netWorth: "Venture Visionary",
    category: "Equity & Ownership",
    quote: "You're not going to get rich renting out your time. You must own equity—a piece of a business—to gain your financial freedom.",
    tip: "Play long-term iterated games with long-term people. Build wealth through ownership of scalable, cash-generating assets and technology leverage.",
  },
  {
    id: "quote-bezos",
    author: "Jeff Bezos",
    title: "Founder & Executive Chairman, Amazon",
    netWorth: "$200 Billion+",
    category: "Long-Term Horizon",
    quote: "When asked why people don't copy his investment thesis, Warren replied: 'Because nobody wants to get rich slowly.'",
    tip: "Focus obsessively on what will not change in the next 10 years. In capital markets, disciplined capital allocation and sustained cash flows consistently compound.",
  },
  {
    id: "quote-templeton",
    author: "Sir John Templeton",
    title: "Global Fund Pioneer & Philanthropist",
    netWorth: "Pioneer of Global Mutual Funds",
    category: "Contrarian Discipline",
    quote: "The four most dangerous words in investing are: 'This time it's different.'",
    tip: "The maximum point of opportunity occurs at the point of maximum pessimism. Maintain liquid dry powder to allocate courageously during broad sell-offs.",
  },
];
