import type { SignalStock, SignalsSummary } from "@/types/Signals";

export const SIGNALS_PAGE_CONFIG = {
  heading: "what moved,",
  headingAccent: "and why.",
  subtitlePattern: "60 signals • 18:07 IST, 9 Oct 2026",
  widgetTitle: "Signals",
  widgetCountSuffix: "now",
  showAllText: "Show all 60",
  backToLiveText: "← Back",
  allSignalsSectionTitle: "ALL SIGNALS",
};

export const SIGNALS_FILTER_OPTIONS = {
  direction: [
    { id: "ALL", label: "Both ways" },
    { id: "UP", label: "▲ Up" },
    { id: "DOWN", label: "▼ Down" },
  ] as const,
  categories: [
    { id: "ALL", label: "Everything" },
    { id: "52_WEEK", label: "52-week highs & lows" },
    { id: "BREAKOUT_20D", label: "20-day breakouts" },
  ] as const,
  widgetPills: [
    { id: "ALL", label: "All" },
    { id: "UP", label: "Up" },
    { id: "DOWN", label: "Down" },
  ] as const,
};

export const INITIAL_SIGNALS_SUMMARY: SignalsSummary = {
  totalSignals: 60,
  totalStocks: 50,
  upCount: 33,
  downCount: 27,
  asOf: "18:07 IST, 9 Oct 2026",
};

export const INITIAL_TOP_HIGHLIGHTS: SignalStock[] = [
  {
    id: "sig-suzlon-1",
    symbol: "SUZLON",
    name: "Suzlon Energy",
    slug: "suzlon",
    price: 37.47,
    change: 1.16,
    changePercent: 3.21,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹36.31 vs 52-week low ₹36.31",
    sector: "CAPITAL GOODS",
    rank: 1,
  },
  {
    id: "sig-dmart-2",
    symbol: "DMART",
    name: "Avenue Supermarts",
    slug: "dmart",
    price: 3497.70,
    change: -63.80,
    changePercent: -1.79,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹3,497.70 vs 52-week low ₹3,497.70",
    sector: "CONSUMER SERVICES",
    rank: 2,
    newsHeadline:
      "DMart Q2 Results: Cons profit rises nearly 9% YoY to Rs 743 crore, margin drops slightly",
    newsSource: "The Economic Times",
    newsTime: "2 h ago",
  },
  {
    id: "sig-tatapower-3",
    symbol: "TATAPOWER",
    name: "Tata Power",
    slug: "tatapower",
    price: 333.60,
    change: 5.50,
    changePercent: 1.68,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹333.60 vs 52-week low ₹333.60",
    sector: "POWER",
    rank: 3,
  },
];

export const INITIAL_ALL_SIGNALS: SignalStock[] = [
  // Exact items from Screenshot 1 & 2
  INITIAL_TOP_HIGHLIGHTS[0],
  INITIAL_TOP_HIGHLIGHTS[1],
  INITIAL_TOP_HIGHLIGHTS[2],
  {
    id: "sig-irfc-4",
    symbol: "IRFC",
    name: "Indian Railway Finance Corp",
    slug: "irfc",
    price: 74.90,
    change: 0.60,
    changePercent: 0.81,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹74.06 vs 52-week low ₹74.06",
    sector: "FINANCE",
    newsHeadline:
      "Navratna PSU IRFC Q2 results, dividend 2026 announcement date, time, earnings schedule, dividend yield, history",
    newsSource: "Livemint",
    newsTime: "3 h ago",
  },
  {
    id: "sig-bel-5",
    symbol: "BEL",
    name: "Bharat Electronics",
    slug: "bel",
    price: 369.95,
    change: 2.65,
    changePercent: 0.72,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹360.50 vs 52-week low ₹360.50",
    sector: "CAPITAL GOODS",
  },
  {
    id: "sig-vaml-6",
    symbol: "VAML",
    name: "Vardhman Acrylics",
    slug: "vaml",
    price: 371.90,
    change: -2.55,
    changePercent: -0.68,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹368.20 vs 52-week low ₹368.20",
    sector: "TEXTILES",
  },
  {
    id: "sig-mazdock-7",
    symbol: "MAZDOCK",
    name: "Mazagon Dock Shipbuilders",
    slug: "mazdock",
    price: 2003.00,
    change: 12.90,
    changePercent: 0.65,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,987.70 vs 52-week low ₹1,987.70",
    sector: "DEFENCE",
  },
  {
    id: "sig-mfsl-8",
    symbol: "MFSL",
    name: "Max Financial Services",
    slug: "mfsl",
    price: 1313.90,
    change: -8.45,
    changePercent: -0.64,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,301.00 vs 52-week low ₹1,301.00",
    sector: "FINANCE",
  },
  {
    id: "sig-reliance-9",
    symbol: "RELIANCE",
    name: "Reliance Industries",
    slug: "reliance",
    price: 1170.90,
    change: -7.05,
    changePercent: -0.60,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,160.20 vs 52-week low ₹1,160.20",
    sector: "ENERGY",
    newsHeadline:
      "Jio Platforms IPO: What does listing of Reliance Industries' company means for Airtel, Vodafone Idea, Indus Towers",
    newsSource: "CNBC TV18",
    newsTime: "4 h ago",
  },
  {
    id: "sig-swiggy-10",
    symbol: "SWIGGY",
    name: "Swiggy Ltd",
    slug: "swiggy",
    price: 234.30,
    change: -0.65,
    changePercent: -0.28,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹232.40 vs 52-week low ₹232.40",
    sector: "CONSUMER TECH",
    newsHeadline:
      "Shopping this Navratri? BOBCARD offers discounts on Swiggy, AJIO, jewellery and groceries",
    newsSource: "Business Standard",
    newsTime: "5 h ago",
  },
  {
    id: "sig-mrf-11",
    symbol: "MRF",
    name: "MRF Limited",
    slug: "mrf",
    price: 122190.00,
    change: -269.00,
    changePercent: -0.22,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,21,870.00 vs 52-week low ₹1,21,870.00",
    sector: "AUTO ANCILLARY",
  },
  {
    id: "sig-vmm-12",
    symbol: "VMM",
    name: "Vardhman Holdings",
    slug: "vmm",
    price: 97.20,
    change: 0.20,
    changePercent: 0.21,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹96.60 vs 52-week low ₹96.60",
    sector: "FINANCE",
  },
  {
    id: "sig-waareeener-13",
    symbol: "WAAREEENER",
    name: "Waaree Energies",
    slug: "waareeener",
    price: 2316.00,
    change: -0.90,
    changePercent: -0.04,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹2,281.80 vs 52-week low ₹2,281.80",
    sector: "RENEWABLE ENERGY",
  },
  // 52-Week High & Breakout companies
  {
    id: "sig-trent-14",
    symbol: "TRENT",
    name: "Trent Ltd",
    slug: "trent",
    price: 7890.00,
    change: 365.00,
    changePercent: 4.85,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹7,910.00 vs 52-week high ₹7,910.00",
    sector: "RETAIL",
    newsHeadline:
      "Trent rallies 5% on strong festive sales outlook across Westside & Zudio stores",
    newsSource: "Moneycontrol",
    newsTime: "1 h ago",
  },
  {
    id: "sig-polycab-15",
    symbol: "POLYCAB",
    name: "Polycab India",
    slug: "polycab",
    price: 6850.00,
    change: 258.00,
    changePercent: 3.92,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹6,880.00 vs 52-week high ₹6,880.00",
    sector: "CAPITAL GOODS",
  },
  {
    id: "sig-kaynes-16",
    symbol: "KAYNES",
    name: "Kaynes Technology",
    slug: "kaynes",
    price: 5420.00,
    change: 264.00,
    changePercent: 5.12,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹5,450.00 vs 52-week high ₹5,450.00",
    sector: "ELECTRONICS",
  },
  {
    id: "sig-dixon-17",
    symbol: "DIXON",
    name: "Dixon Technologies",
    slug: "dixon",
    price: 14250.00,
    change: 395.00,
    changePercent: 2.85,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹14,300.00 vs 52-week high ₹14,300.00",
    sector: "MANUFACTURING",
  },
  {
    id: "sig-bhartiartl-18",
    symbol: "BHARTIARTL",
    name: "Bharti Airtel",
    slug: "bhartiartl",
    price: 1833.90,
    change: 23.30,
    changePercent: 1.29,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹1,840.00 vs 52-week high ₹1,840.00",
    sector: "TELECOM",
  },
  {
    id: "sig-sunpharma-19",
    symbol: "SUNPHARMA",
    name: "Sun Pharma",
    slug: "sunpharma",
    price: 1890.25,
    change: 8.15,
    changePercent: 0.43,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹1,895.00 vs 52-week high ₹1,895.00",
    sector: "PHARMA",
  },
  {
    id: "sig-hdfcbank-20",
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    slug: "hdfcbank",
    price: 1682.40,
    change: 8.85,
    changePercent: 0.53,
    type: "52_WEEK_LOW",
    direction: "UP",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,675.00 vs 52-week low ₹1,675.00",
    sector: "BANKING",
  },
  {
    id: "sig-icicibank-21",
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    slug: "icicibank",
    price: 1357.50,
    change: 14.60,
    changePercent: 1.09,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹1,362.00 vs 52-week high ₹1,362.00",
    sector: "BANKING",
  },
  {
    id: "sig-coalindia-22",
    symbol: "COALINDIA",
    name: "Coal India",
    slug: "coalindia",
    price: 414.50,
    change: 2.85,
    changePercent: 0.69,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹412.00",
    sector: "ENERGY",
  },
  {
    id: "sig-bse-23",
    symbol: "BSE",
    name: "BSE Ltd",
    slug: "bse",
    price: 3356.00,
    change: 50.80,
    changePercent: 1.54,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹3,320.00",
    sector: "FINANCE",
  },
  {
    id: "sig-tcs-24",
    symbol: "TCS",
    name: "Tata Consultancy Services",
    slug: "tcs",
    price: 4218.75,
    change: -18.30,
    changePercent: -0.43,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹4,200.00 vs 52-week low ₹4,200.00",
    sector: "IT",
  },
  {
    id: "sig-infy-25",
    symbol: "INFY",
    name: "Infosys",
    slug: "infy",
    price: 1895.30,
    change: -24.70,
    changePercent: -1.29,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,880.00 vs 52-week low ₹1,880.00",
    sector: "IT",
  },
  {
    id: "sig-sbin-26",
    symbol: "SBIN",
    name: "State Bank of India",
    slug: "sbin",
    price: 792.65,
    change: 4.80,
    changePercent: 0.61,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹795.00 vs 52-week high ₹795.00",
    sector: "BANKING",
  },
  {
    id: "sig-zomato-27",
    symbol: "ZOMATO",
    name: "Zomato Ltd",
    slug: "zomato",
    price: 275.40,
    change: 1.40,
    changePercent: 0.51,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day resistance ₹272.00",
    sector: "CONSUMER TECH",
  },
  {
    id: "sig-itc-28",
    symbol: "ITC",
    name: "ITC Ltd",
    slug: "itc",
    price: 504.20,
    change: -4.10,
    changePercent: -0.81,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹501.00 vs 52-week low ₹501.00",
    sector: "FMCG",
  },
  {
    id: "sig-maruti-29",
    symbol: "MARUTI",
    name: "Maruti Suzuki",
    slug: "maruti",
    price: 12840.00,
    change: -185.00,
    changePercent: -1.42,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹12,780.00 vs 52-week low ₹12,780.00",
    sector: "AUTO",
  },
  {
    id: "sig-eichermot-30",
    symbol: "EICHERMOT",
    name: "Eicher Motors",
    slug: "eichermot",
    price: 4890.30,
    change: 64.00,
    changePercent: 1.33,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹4,910.00 vs 52-week high ₹4,910.00",
    sector: "AUTO",
  },
  {
    id: "sig-bajajauto-31",
    symbol: "BAJAJ-AUTO",
    name: "Bajaj Auto",
    slug: "bajaj-auto",
    price: 11980.00,
    change: 180.00,
    changePercent: 1.53,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹12,020.00 vs 52-week high ₹12,020.00",
    sector: "AUTO",
  },
  {
    id: "sig-apollohosp-32",
    symbol: "APOLLOHOSP",
    name: "Apollo Hospitals",
    slug: "apollohosp",
    price: 7150.00,
    change: 85.00,
    changePercent: 1.20,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹7,180.00 vs 52-week high ₹7,180.00",
    sector: "HEALTHCARE",
  },
  {
    id: "sig-divislab-33",
    symbol: "DIVISLAB",
    name: "Divi's Laboratories",
    slug: "divislab",
    price: 5410.00,
    change: 72.00,
    changePercent: 1.35,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹5,440.00 vs 52-week high ₹5,440.00",
    sector: "PHARMA",
  },
  {
    id: "sig-shriramfin-34",
    symbol: "SHRIRAMFIN",
    name: "Shriram Finance",
    slug: "shriramfin",
    price: 3340.00,
    change: 51.00,
    changePercent: 1.55,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹3,360.00 vs 52-week high ₹3,360.00",
    sector: "FINANCE",
  },
  {
    id: "sig-jiofin-35",
    symbol: "JIOFIN",
    name: "Jio Financial Services",
    slug: "jiofin",
    price: 348.60,
    change: 2.10,
    changePercent: 0.61,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹346.00",
    sector: "FINANCE",
  },
  {
    id: "sig-bpcl-36",
    symbol: "BPCL",
    name: "Bharat Petroleum",
    slug: "bpcl",
    price: 348.15,
    change: 4.80,
    changePercent: 1.40,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹350.00 vs 52-week high ₹350.00",
    sector: "ENERGY",
  },
  {
    id: "sig-tataconsum-37",
    symbol: "TATACONSUM",
    name: "Tata Consumer Products",
    slug: "tataconsum",
    price: 1184.60,
    change: 9.30,
    changePercent: 0.79,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹1,190.00 vs 52-week high ₹1,190.00",
    sector: "FMCG",
  },
  {
    id: "sig-heromotoco-38",
    symbol: "HEROMOTOCO",
    name: "Hero MotoCorp",
    slug: "heromotoco",
    price: 5740.00,
    change: 62.00,
    changePercent: 1.09,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹5,760.00 vs 52-week high ₹5,760.00",
    sector: "AUTO",
  },
  {
    id: "sig-hindalco-39",
    symbol: "HINDALCO",
    name: "Hindalco Industries",
    slug: "hindalco",
    price: 712.30,
    change: 3.40,
    changePercent: 0.48,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹716.00 vs 52-week high ₹716.00",
    sector: "METALS",
  },
  {
    id: "sig-jswsteel-40",
    symbol: "JSWSTEEL",
    name: "JSW Steel",
    slug: "jswsteel",
    price: 985.60,
    change: 4.10,
    changePercent: 0.42,
    type: "52_WEEK_HIGH",
    direction: "UP",
    statusText: "At a 52-week high",
    comparisonText: "High ₹990.00 vs 52-week high ₹990.00",
    sector: "METALS",
  },
  {
    id: "sig-tatamotors-41",
    symbol: "TATAMOTORS",
    name: "Tata Motors",
    slug: "tatamotors",
    price: 978.40,
    change: -21.20,
    changePercent: -2.12,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹972.00 vs 52-week low ₹972.00",
    sector: "AUTO",
  },
  {
    id: "sig-hindunilvr-42",
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever",
    slug: "hindunilvr",
    price: 2785.40,
    change: -40.60,
    changePercent: -1.44,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹2,770.00 vs 52-week low ₹2,770.00",
    sector: "FMCG",
  },
  {
    id: "sig-asianpaint-43",
    symbol: "ASIANPAINT",
    name: "Asian Paints",
    slug: "asianpaint",
    price: 3180.20,
    change: -45.50,
    changePercent: -1.41,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹3,160.00 vs 52-week low ₹3,160.00",
    sector: "PAINTS",
  },
  {
    id: "sig-titan-44",
    symbol: "TITAN",
    name: "Titan Company",
    slug: "titan",
    price: 3680.15,
    change: -55.40,
    changePercent: -1.48,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹3,660.00 vs 52-week low ₹3,660.00",
    sector: "CONSUMER",
  },
  {
    id: "sig-adaniports-45",
    symbol: "ADANIPORTS",
    name: "Adani Ports & SEZ",
    slug: "adaniports",
    price: 1460.80,
    change: -22.50,
    changePercent: -1.52,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,450.00 vs 52-week low ₹1,450.00",
    sector: "INFRA",
  },
  {
    id: "sig-powergrid-46",
    symbol: "POWERGRID",
    name: "Power Grid Corp",
    slug: "powergrid",
    price: 342.60,
    change: -5.80,
    changePercent: -1.67,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹340.00 vs 52-week low ₹340.00",
    sector: "POWER",
  },
  {
    id: "sig-techm-47",
    symbol: "TECHM",
    name: "Tech Mahindra",
    slug: "techm",
    price: 1620.40,
    change: -27.80,
    changePercent: -1.69,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,610.00 vs 52-week low ₹1,610.00",
    sector: "IT",
  },
  {
    id: "sig-ntpc-48",
    symbol: "NTPC",
    name: "NTPC Ltd",
    slug: "ntpc",
    price: 412.80,
    change: -7.70,
    changePercent: -1.83,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹410.00 vs 52-week low ₹410.00",
    sector: "POWER",
  },
  {
    id: "sig-drreddy-49",
    symbol: "DRREDDY",
    name: "Dr. Reddy's Labs",
    slug: "drreddy",
    price: 6590.00,
    change: -68.00,
    changePercent: -1.02,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹6,550.00 vs 52-week low ₹6,550.00",
    sector: "PHARMA",
  },
  {
    id: "sig-grasim-50",
    symbol: "GRASIM",
    name: "Grasim Industries",
    slug: "grasim",
    price: 2685.00,
    change: -38.40,
    changePercent: -1.41,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹2,670.00 vs 52-week low ₹2,670.00",
    sector: "MATERIALS",
  },
  {
    id: "sig-ltim-51",
    symbol: "LTIM",
    name: "LTIMindtree",
    slug: "ltim",
    price: 6180.00,
    change: -24.00,
    changePercent: -0.39,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹6,150.00 vs 52-week low ₹6,150.00",
    sector: "IT",
  },
  {
    id: "sig-wipro-52",
    symbol: "WIPRO",
    name: "Wipro Ltd",
    slug: "wipro",
    price: 548.20,
    change: -2.40,
    changePercent: -0.44,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹545.00 vs 52-week low ₹545.00",
    sector: "IT",
  },
  {
    id: "sig-britannia-53",
    symbol: "BRITANNIA",
    name: "Britannia Industries",
    slug: "britannia",
    price: 5920.00,
    change: -15.00,
    changePercent: -0.25,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹5,900.00 vs 52-week low ₹5,900.00",
    sector: "FMCG",
  },
  {
    id: "sig-hcltech-54",
    symbol: "HCLTECH",
    name: "HCL Technologies",
    slug: "hcltech",
    price: 1795.60,
    change: -19.40,
    changePercent: -1.07,
    type: "52_WEEK_LOW",
    direction: "DOWN",
    statusText: "At a 52-week low",
    comparisonText: "Low ₹1,780.00 vs 52-week low ₹1,780.00",
    sector: "IT",
  },
  {
    id: "sig-lt-55",
    symbol: "LT",
    name: "Larsen & Toubro",
    slug: "lt",
    price: 3624.80,
    change: 18.50,
    changePercent: 0.51,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹3,610.00",
    sector: "INFRA",
  },
  {
    id: "sig-bajfinance-56",
    symbol: "BAJFINANCE",
    name: "Bajaj Finance",
    slug: "bajfinance",
    price: 7380.00,
    change: 42.50,
    changePercent: 0.58,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹7,350.00",
    sector: "FINANCE",
  },
  {
    id: "sig-adanient-57",
    symbol: "ADANIENT",
    name: "Adani Enterprises",
    slug: "adanient",
    price: 3125.70,
    change: 15.80,
    changePercent: 0.51,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹3,110.00",
    sector: "CONGLOMERATE",
  },
  {
    id: "sig-kotakbank-58",
    symbol: "KOTAKBANK",
    name: "Kotak Mahindra Bank",
    slug: "kotakbank",
    price: 1840.00,
    change: 34.00,
    changePercent: 1.88,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day resistance ₹1,820.00",
    sector: "BANKING",
  },
  {
    id: "sig-axisbank-59",
    symbol: "AXISBANK",
    name: "Axis Bank",
    slug: "axisbank",
    price: 1195.30,
    change: 6.60,
    changePercent: 0.55,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day high ₹1,190.00",
    sector: "BANKING",
  },
  {
    id: "sig-ongc-60",
    symbol: "ONGC",
    name: "Oil & Natural Gas Corp",
    slug: "ongc",
    price: 298.45,
    change: 1.10,
    changePercent: 0.37,
    type: "BREAKOUT_20D",
    direction: "UP",
    statusText: "20-day breakout",
    comparisonText: "Crossed 20-day resistance ₹296.00",
    sector: "ENERGY",
  },
];
