import type { SectorMoveItem } from "@/types/StockNewsSection";

export const STOCK_NEWS_TABS = [
  { id: "trending", label: "Trending" },
  { id: "sector", label: "Sector moves" },
] as const;

export const STOCK_NEWS_LABELS = {
  subtitleTemplate: (symbol: string) =>
    `Latest news about ${symbol}, newest first. Headlines as published by each source.`,
  emptyState: "No recent news found for this ticker. Checking market wire...",
  summaryPrefix: "Summary",
  sectorSubtitle: "Sector-wide performance across Indian equities. Advances, declines, and top relative strength candidates.",
};

export const SECTOR_MOVES_DATA: SectorMoveItem[] = [
  {
    id: "consumer-services",
    name: "Consumer Services",
    changePercent: 0.07,
    upCount: 4,
    downCount: 8,
    totalCount: 12,
    bestStock: "JUBLFOOD",
  },
  {
    id: "financial-services",
    name: "Financial Services",
    changePercent: -0.13,
    upCount: 20,
    downCount: 28,
    totalCount: 48,
    bestStock: "MAHABANK",
  },
  {
    id: "telecom",
    name: "Telecommunications",
    changePercent: -0.32,
    upCount: 1,
    downCount: 3,
    totalCount: 4,
    bestStock: "BHARTIARTL",
  },
  {
    id: "healthcare",
    name: "Healthcare",
    changePercent: -0.42,
    upCount: 5,
    downCount: 9,
    totalCount: 15,
    bestStock: "FORTIS",
  },
  {
    id: "capital-goods",
    name: "Capital Goods",
    changePercent: -0.47,
    upCount: 9,
    downCount: 15,
    totalCount: 24,
    bestStock: "KEI",
  },
  {
    id: "consumer-durables",
    name: "Consumer Durables",
    changePercent: -0.52,
    upCount: 4,
    downCount: 4,
    totalCount: 8,
    bestStock: "KALYANKJIL",
  },
  {
    id: "oil-gas",
    name: "Oil & Gas",
    changePercent: -0.73,
    upCount: 2,
    downCount: 7,
    totalCount: 9,
    bestStock: "OIL",
  },
  {
    id: "it",
    name: "IT",
    changePercent: -0.92,
    upCount: 1,
    downCount: 9,
    totalCount: 10,
    bestStock: "OFSS",
  },
  {
    id: "textiles",
    name: "Textiles",
    changePercent: -1.05,
    upCount: 0,
    downCount: 1,
    totalCount: 1,
    bestStock: "PAGEIND",
  },
  {
    id: "construction-materials",
    name: "Construction Materials",
    changePercent: -1.25,
    upCount: 0,
    downCount: 3,
    totalCount: 3,
    bestStock: "ULTRACEMCO",
  },
  {
    id: "power",
    name: "Power",
    changePercent: -1.37,
    upCount: 1,
    downCount: 8,
    totalCount: 9,
    bestStock: "ADANIGREEN",
  },
  {
    id: "chemicals",
    name: "Chemicals",
    changePercent: -1.45,
    upCount: 0,
    downCount: 5,
    totalCount: 5,
    bestStock: "SOLARINDS",
  },
  {
    id: "auto",
    name: "Auto",
    changePercent: -1.49,
    upCount: 0,
    downCount: 14,
    totalCount: 14,
    bestStock: "MOTHERSON",
  },
  {
    id: "services",
    name: "Services",
    changePercent: -1.61,
    upCount: 0,
    downCount: 4,
    totalCount: 4,
    bestStock: "INDIGO",
  },
  {
    id: "construction",
    name: "Construction",
    changePercent: -1.64,
    upCount: 0,
    downCount: 2,
    totalCount: 2,
    bestStock: "RVNL",
  },
  {
    id: "realty",
    name: "Realty",
    changePercent: -1.87,
    upCount: 0,
    downCount: 6,
    totalCount: 6,
    bestStock: "OBEROIRLTY",
  },
];
